name = "LinearNoiseApproximation"
uuid = "9859b720-004f-4db5-b836-c34ec215a307"
authors = ["Xiaoming Fu"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
